# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.sso_settings_update_request_base_v1 import SsoSettingsUpdateRequestBaseV1

class TestSsoSettingsUpdateRequestBaseV1(unittest.TestCase):
    """SsoSettingsUpdateRequestBaseV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SsoSettingsUpdateRequestBaseV1:
        """Test SsoSettingsUpdateRequestBaseV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SsoSettingsUpdateRequestBaseV1`
        """
        model = SsoSettingsUpdateRequestBaseV1()
        if include_optional:
            return SsoSettingsUpdateRequestBaseV1(
                type = 'SAML'
            )
        else:
            return SsoSettingsUpdateRequestBaseV1(
                type = 'SAML',
        )
        """

    def testSsoSettingsUpdateRequestBaseV1(self):
        """Test SsoSettingsUpdateRequestBaseV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
