# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.list_audit_events_response import ListAuditEventsResponse

class TestListAuditEventsResponse(unittest.TestCase):
    """ListAuditEventsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAuditEventsResponse:
        """Test ListAuditEventsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAuditEventsResponse`
        """
        model = ListAuditEventsResponse()
        if include_optional:
            return ListAuditEventsResponse(
                page = sysdig_client.models.audit_page.AuditPage(
                    total = 10, 
                    prev = 'LTltNGUybXIwdWkzZThhMjE1bjRn', 
                    next = 'KzltNGUybXIwdWkzZThhMjE1bjRn', ),
                data = [
                    sysdig_client.models.audit_event.AuditEvent(
                        id = '15cbf54e34df95404caad1c988cf7c42', 
                        cursor = 'LTltNGUybXIwdWkzZThhMjE1bjRn', 
                        timestamp = 1617220000000000000, 
                        content = sysdig_client.models.audit_trail_content.AuditTrailContent(
                            timestamp_ns = 1617220000000000000, 
                            user_id = 122, 
                            username = 'joendoe', 
                            team_id = 13, 
                            team_name = 'Security Operations', 
                            request_method = 'GET', 
                            request_uri = '/api/v1/audit', 
                            user_origin_ip = '22.220.145.219', 
                            query_string = 'controlId=1&resourceKind=workload', 
                            response_status_code = 200, 
                            entity_type = 'policy', 
                            entity_id = '', 
                            entity_payload = 'SAMLResponse=***&RelayState=%23%2F%26customer%3D5', 
                            service_account_id = 123, 
                            service_account_name = 'service-account-1', ), 
                        labels = {"entityType":"auth"}, )
                    ]
            )
        else:
            return ListAuditEventsResponse(
                page = sysdig_client.models.audit_page.AuditPage(
                    total = 10, 
                    prev = 'LTltNGUybXIwdWkzZThhMjE1bjRn', 
                    next = 'KzltNGUybXIwdWkzZThhMjE1bjRn', ),
                data = [
                    sysdig_client.models.audit_event.AuditEvent(
                        id = '15cbf54e34df95404caad1c988cf7c42', 
                        cursor = 'LTltNGUybXIwdWkzZThhMjE1bjRn', 
                        timestamp = 1617220000000000000, 
                        content = sysdig_client.models.audit_trail_content.AuditTrailContent(
                            timestamp_ns = 1617220000000000000, 
                            user_id = 122, 
                            username = 'joendoe', 
                            team_id = 13, 
                            team_name = 'Security Operations', 
                            request_method = 'GET', 
                            request_uri = '/api/v1/audit', 
                            user_origin_ip = '22.220.145.219', 
                            query_string = 'controlId=1&resourceKind=workload', 
                            response_status_code = 200, 
                            entity_type = 'policy', 
                            entity_id = '', 
                            entity_payload = 'SAMLResponse=***&RelayState=%23%2F%26customer%3D5', 
                            service_account_id = 123, 
                            service_account_name = 'service-account-1', ), 
                        labels = {"entityType":"auth"}, )
                    ],
        )
        """

    def testListAuditEventsResponse(self):
        """Test ListAuditEventsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
