# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.all_sso_settings_response_v1 import AllSsoSettingsResponseV1

class TestAllSsoSettingsResponseV1(unittest.TestCase):
    """AllSsoSettingsResponseV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AllSsoSettingsResponseV1:
        """Test AllSsoSettingsResponseV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AllSsoSettingsResponseV1`
        """
        model = AllSsoSettingsResponseV1()
        if include_optional:
            return AllSsoSettingsResponseV1(
                data = [
                    sysdig_client.models.sso_settings_write_response_v1.SSO Settings Write Response V1()
                    ]
            )
        else:
            return AllSsoSettingsResponseV1(
        )
        """

    def testAllSsoSettingsResponseV1(self):
        """Test AllSsoSettingsResponseV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
