# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.update_custom_webhook_notification_channel_request_v1 import UpdateCustomWebhookNotificationChannelRequestV1

class TestUpdateCustomWebhookNotificationChannelRequestV1(unittest.TestCase):
    """UpdateCustomWebhookNotificationChannelRequestV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateCustomWebhookNotificationChannelRequestV1:
        """Test UpdateCustomWebhookNotificationChannelRequestV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateCustomWebhookNotificationChannelRequestV1`
        """
        model = UpdateCustomWebhookNotificationChannelRequestV1()
        if include_optional:
            return UpdateCustomWebhookNotificationChannelRequestV1(
                options = None
            )
        else:
            return UpdateCustomWebhookNotificationChannelRequestV1(
                options = None,
        )
        """

    def testUpdateCustomWebhookNotificationChannelRequestV1(self):
        """Test UpdateCustomWebhookNotificationChannelRequestV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
