# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.slack_create_notification_channel_options_v1 import SlackCreateNotificationChannelOptionsV1

class TestSlackCreateNotificationChannelOptionsV1(unittest.TestCase):
    """SlackCreateNotificationChannelOptionsV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SlackCreateNotificationChannelOptionsV1:
        """Test SlackCreateNotificationChannelOptionsV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SlackCreateNotificationChannelOptionsV1`
        """
        model = SlackCreateNotificationChannelOptionsV1()
        if include_optional:
            return SlackCreateNotificationChannelOptionsV1(
                has_hiding_of_sensitive_info = True,
                channel = '\@some.user',
                url = 'https://hooks.slack.com/TXXXXX/BXXXXX/XXXXXXXXXX',
                is_private_channel = False,
                private_channel_url = 'https://app.slack.com/client/TXXXXXXXX/CXXXXXXXXXX'
            )
        else:
            return SlackCreateNotificationChannelOptionsV1(
                url = 'https://hooks.slack.com/TXXXXX/BXXXXX/XXXXXXXXXX',
        )
        """

    def testSlackCreateNotificationChannelOptionsV1(self):
        """Test SlackCreateNotificationChannelOptionsV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
