# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.cvss_score import CvssScore

class TestCvssScore(unittest.TestCase):
    """CvssScore unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CvssScore:
        """Test CvssScore
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CvssScore`
        """
        model = CvssScore()
        if include_optional:
            return CvssScore(
                version = '3.0.0',
                score = 1,
                vector = 'CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H'
            )
        else:
            return CvssScore(
                version = '3.0.0',
                score = 1,
        )
        """

    def testCvssScore(self):
        """Test CvssScore"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
