# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.create_webhook_integration_request_all_of_connection_info import CreateWebhookIntegrationRequestAllOfConnectionInfo

class TestCreateWebhookIntegrationRequestAllOfConnectionInfo(unittest.TestCase):
    """CreateWebhookIntegrationRequestAllOfConnectionInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateWebhookIntegrationRequestAllOfConnectionInfo:
        """Test CreateWebhookIntegrationRequestAllOfConnectionInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateWebhookIntegrationRequestAllOfConnectionInfo`
        """
        model = CreateWebhookIntegrationRequestAllOfConnectionInfo()
        if include_optional:
            return CreateWebhookIntegrationRequestAllOfConnectionInfo(
                endpoint = 'https://endpoint.mydomain.com',
                is_insecure = False,
                headers = [
                    sysdig_client.models.key_value_object_representation.Key-value object representation(
                        key = 'mykey', 
                        value = 'myvalue', )
                    ],
                output = 'json',
                timestamp_format = 'nanoseconds',
                auth = 'BASIC_AUTH',
                certificate_id = 1,
                secret = 'eiMaimiYohrahbaeS6iaNgo8iu'
            )
        else:
            return CreateWebhookIntegrationRequestAllOfConnectionInfo(
                endpoint = 'https://endpoint.mydomain.com',
                auth = 'BASIC_AUTH',
                secret = 'eiMaimiYohrahbaeS6iaNgo8iu',
        )
        """

    def testCreateWebhookIntegrationRequestAllOfConnectionInfo(self):
        """Test CreateWebhookIntegrationRequestAllOfConnectionInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
