# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.create_ms_teams_notification_channel_request_v1 import CreateMsTeamsNotificationChannelRequestV1

class TestCreateMsTeamsNotificationChannelRequestV1(unittest.TestCase):
    """CreateMsTeamsNotificationChannelRequestV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateMsTeamsNotificationChannelRequestV1:
        """Test CreateMsTeamsNotificationChannelRequestV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateMsTeamsNotificationChannelRequestV1`
        """
        model = CreateMsTeamsNotificationChannelRequestV1()
        if include_optional:
            return CreateMsTeamsNotificationChannelRequestV1(
                options = None
            )
        else:
            return CreateMsTeamsNotificationChannelRequestV1(
                options = None,
        )
        """

    def testCreateMsTeamsNotificationChannelRequestV1(self):
        """Test CreateMsTeamsNotificationChannelRequestV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
