# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.base_connection_info_amazon_sqs import BaseConnectionInfoAmazonSqs

class TestBaseConnectionInfoAmazonSqs(unittest.TestCase):
    """BaseConnectionInfoAmazonSqs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BaseConnectionInfoAmazonSqs:
        """Test BaseConnectionInfoAmazonSqs
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BaseConnectionInfoAmazonSqs`
        """
        model = BaseConnectionInfoAmazonSqs()
        if include_optional:
            return BaseConnectionInfoAmazonSqs(
                owner_account = '123456789012',
                region = 'us-east',
                queue = 'sysdig-efo-queue',
                delay = 1,
                headers = [
                    sysdig_client.models.key_value_object_representation.Key-value object representation(
                        key = 'mykey', 
                        value = 'myvalue', )
                    ]
            )
        else:
            return BaseConnectionInfoAmazonSqs(
                region = 'us-east',
                queue = 'sysdig-efo-queue',
        )
        """

    def testBaseConnectionInfoAmazonSqs(self):
        """Test BaseConnectionInfoAmazonSqs"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
