# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.zone_response_v1 import ZoneResponseV1

class TestZoneResponseV1(unittest.TestCase):
    """ZoneResponseV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ZoneResponseV1:
        """Test ZoneResponseV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ZoneResponseV1`
        """
        model = ZoneResponseV1()
        if include_optional:
            return ZoneResponseV1(
                id = 1,
                name = 'Production',
                description = 'Production Environment',
                author = 'Sysdig',
                last_modified_by = 'john_doe@sysdig.com',
                last_updated = 1,
                is_system = False,
                scopes = [
                    sysdig_client.models.zone_scope.Zone Scope(
                        id = 1, 
                        target_type = 'target', 
                        rules = 'clusterId in ( "test" )', )
                    ]
            )
        else:
            return ZoneResponseV1(
        )
        """

    def testZoneResponseV1(self):
        """Test ZoneResponseV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
