# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.group_mapping_settings_v1 import GroupMappingSettingsV1

class TestGroupMappingSettingsV1(unittest.TestCase):
    """GroupMappingSettingsV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupMappingSettingsV1:
        """Test GroupMappingSettingsV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupMappingSettingsV1`
        """
        model = GroupMappingSettingsV1()
        if include_optional:
            return GroupMappingSettingsV1(
                no_mapping_strategy = 'UNAUTHORIZED',
                different_roles_same_team_strategy = 'UNAUTHORIZED',
                no_mappings_error_redirect_url = 'https://www.example.com'
            )
        else:
            return GroupMappingSettingsV1(
                no_mapping_strategy = 'UNAUTHORIZED',
                different_roles_same_team_strategy = 'UNAUTHORIZED',
        )
        """

    def testGroupMappingSettingsV1(self):
        """Test GroupMappingSettingsV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
