# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.integration_response_v1 import IntegrationResponseV1

class TestIntegrationResponseV1(unittest.TestCase):
    """IntegrationResponseV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IntegrationResponseV1:
        """Test IntegrationResponseV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IntegrationResponseV1`
        """
        model = IntegrationResponseV1()
        if include_optional:
            return IntegrationResponseV1(
                id = 1,
                name = 'name',
                created_at = '2023-09-06T12:30:45Z',
                modified_at = '2023-09-06T12:30:45Z',
                deleted_at = '2023-09-06T12:30:45Z',
                customer_id = 1,
                is_enabled = False,
                is_valid = False,
                is_all_teams = False,
                team_ids = [
                    1
                    ],
                jira_project_id = '10000',
                jira_project_name = 'jira-project-name',
                jira_url = 'https://atlassian-url.com',
                jira_email = 'jira.user@email.com',
                jira_assignee = '5b10ac8d82e05b22cc7d4ef5',
                jira_labels = [
                    'label'
                    ],
                parent_issue_type = sysdig_client.models.jira_issue_type_response_v1.Jira Issue Type Response V1(
                    id = null, 
                    jira_id = '1', 
                    jira_name = 'jira-name', 
                    jira_hierarchy_level = 1, 
                    jira_open_status_id = '1000', 
                    jira_in_progress_status_id = '1001', 
                    jira_closed_status_id = '1002', 
                    standard_fields = [
                        sysdig_client.models.jira_issue_type_field_response_v1.Jira Issue Type Field Response V1(
                            id = null, 
                            jira_id = 'jira-id', 
                            jira_name = 'jira-name', 
                            type = 'checkbox', 
                            is_required = True, 
                            has_default_value = False, 
                            allowed_values = [
                                null
                                ], )
                        ], 
                    custom_fields = [
                        sysdig_client.models.jira_issue_type_field_response_v1.Jira Issue Type Field Response V1(
                            id = null, 
                            jira_id = 'jira-id', 
                            jira_name = 'jira-name', 
                            type = 'checkbox', 
                            is_required = True, 
                            has_default_value = False, )
                        ], ),
                child_issue_type = sysdig_client.models.jira_issue_type_response_v1.Jira Issue Type Response V1(
                    id = null, 
                    jira_id = '1', 
                    jira_name = 'jira-name', 
                    jira_hierarchy_level = 1, 
                    jira_open_status_id = '1000', 
                    jira_in_progress_status_id = '1001', 
                    jira_closed_status_id = '1002', 
                    standard_fields = [
                        sysdig_client.models.jira_issue_type_field_response_v1.Jira Issue Type Field Response V1(
                            id = null, 
                            jira_id = 'jira-id', 
                            jira_name = 'jira-name', 
                            type = 'checkbox', 
                            is_required = True, 
                            has_default_value = False, 
                            allowed_values = [
                                null
                                ], )
                        ], 
                    custom_fields = [
                        sysdig_client.models.jira_issue_type_field_response_v1.Jira Issue Type Field Response V1(
                            id = null, 
                            jira_id = 'jira-id', 
                            jira_name = 'jira-name', 
                            type = 'checkbox', 
                            is_required = True, 
                            has_default_value = False, )
                        ], )
            )
        else:
            return IntegrationResponseV1(
                id = 1,
                name = 'name',
                created_at = '2023-09-06T12:30:45Z',
                modified_at = '2023-09-06T12:30:45Z',
                customer_id = 1,
                is_enabled = False,
                is_valid = False,
                is_all_teams = False,
                jira_project_id = '10000',
                jira_url = 'https://atlassian-url.com',
                jira_email = 'jira.user@email.com',
        )
        """

    def testIntegrationResponseV1(self):
        """Test IntegrationResponseV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
