# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.workload_cost_trends_data_response import WorkloadCostTrendsDataResponse

class TestWorkloadCostTrendsDataResponse(unittest.TestCase):
    """WorkloadCostTrendsDataResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkloadCostTrendsDataResponse:
        """Test WorkloadCostTrendsDataResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkloadCostTrendsDataResponse`
        """
        model = WorkloadCostTrendsDataResponse()
        if include_optional:
            return WorkloadCostTrendsDataResponse(
                current_range = None,
                previous_range = None,
                total = sysdig_client.models.workload_cost_trends_data_response_total.WorkloadCostTrendsDataResponse_total(
                    current = 33.754530610617486, 
                    previous = 34.36367482352418, 
                    change = -1.77, ),
                scope = [
                    sysdig_client.models.prom_ql_matcher.PromQL Matcher(
                        label = 'kube_cluster_name', 
                        operator = 'REGEX_MATCH', 
                        value = 'my_service.*', )
                    ],
                group_by = [
                    'kube_cluster_name'
                    ],
                group_by_data = [
                    sysdig_client.models.workload_cost_trends_data_response_group_by_data_inner.WorkloadCostTrendsDataResponse_groupByData_inner(
                        group = {
                            'key' : 'kube_cluster_name:test-k8s-cluster'
                            }, 
                        current = 33.754530610617486, 
                        previous = 34.36367482352418, 
                        change = -0.6091442129, )
                    ]
            )
        else:
            return WorkloadCostTrendsDataResponse(
        )
        """

    def testWorkloadCostTrendsDataResponse(self):
        """Test WorkloadCostTrendsDataResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
