# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.action_outputs_metadata import ActionOutputsMetadata

class TestActionOutputsMetadata(unittest.TestCase):
    """ActionOutputsMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActionOutputsMetadata:
        """Test ActionOutputsMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActionOutputsMetadata`
        """
        model = ActionOutputsMetadata()
        if include_optional:
            return ActionOutputsMetadata(
                name = 'quarantined_file_path',
                description = 'An absolute path',
                type = 'integer',
                required = True
            )
        else:
            return ActionOutputsMetadata(
                name = 'quarantined_file_path',
                description = 'An absolute path',
                type = 'integer',
                required = True,
        )
        """

    def testActionOutputsMetadata(self):
        """Test ActionOutputsMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
