# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.image_config_default_user_list import ImageConfigDefaultUserList

class TestImageConfigDefaultUserList(unittest.TestCase):
    """ImageConfigDefaultUserList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ImageConfigDefaultUserList:
        """Test ImageConfigDefaultUserList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageConfigDefaultUserList`
        """
        model = ImageConfigDefaultUserList()
        if include_optional:
            return ImageConfigDefaultUserList(
                type = 'imageConfigDefaultUserList',
                extra = sysdig_client.models.image_config_default_user_list_extra.ImageConfigDefaultUserList_extra(
                    operator = 'IN', 
                    users = ["root","admin"], )
            )
        else:
            return ImageConfigDefaultUserList(
                type = 'imageConfigDefaultUserList',
                extra = sysdig_client.models.image_config_default_user_list_extra.ImageConfigDefaultUserList_extra(
                    operator = 'IN', 
                    users = ["root","admin"], ),
        )
        """

    def testImageConfigDefaultUserList(self):
        """Test ImageConfigDefaultUserList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
