# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.additional_team_permissions_v1 import AdditionalTeamPermissionsV1

class TestAdditionalTeamPermissionsV1(unittest.TestCase):
    """AdditionalTeamPermissionsV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdditionalTeamPermissionsV1:
        """Test AdditionalTeamPermissionsV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdditionalTeamPermissionsV1`
        """
        model = AdditionalTeamPermissionsV1()
        if include_optional:
            return AdditionalTeamPermissionsV1(
                has_sysdig_captures = False,
                has_infrastructure_events = False,
                has_aws_data = False,
                has_rapid_response = False,
                has_agent_cli = False,
                has_beacon_metrics = False
            )
        else:
            return AdditionalTeamPermissionsV1(
        )
        """

    def testAdditionalTeamPermissionsV1(self):
        """Test AdditionalTeamPermissionsV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
