# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.list_bundles_response import ListBundlesResponse

class TestListBundlesResponse(unittest.TestCase):
    """ListBundlesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListBundlesResponse:
        """Test ListBundlesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListBundlesResponse`
        """
        model = ListBundlesResponse()
        if include_optional:
            return ListBundlesResponse(
                page = sysdig_client.models.policies_page.PoliciesPage(
                    returned = 1, 
                    matched = 10, 
                    next = 'MA==', ),
                data = [
                    sysdig_client.models.get_bundle_response.GetBundleResponse(
                        id = 1, 
                        name = 'Sysdig Bundle', 
                        identifier = 'sysdig-bundle', 
                        description = 'Default Sysdig Bundle', 
                        bundle_type = 'custom', 
                        rules = [
                            sysdig_client.models.bundle_rule.BundleRule(
                                rule_type = 'vulnDenyList', 
                                predicates = [{"type":"vulnSeverity","extra":{"level":"high"}}], 
                                rule_id = '42', )
                            ], )
                    ]
            )
        else:
            return ListBundlesResponse(
                page = sysdig_client.models.policies_page.PoliciesPage(
                    returned = 1, 
                    matched = 10, 
                    next = 'MA==', ),
                data = [
                    sysdig_client.models.get_bundle_response.GetBundleResponse(
                        id = 1, 
                        name = 'Sysdig Bundle', 
                        identifier = 'sysdig-bundle', 
                        description = 'Default Sysdig Bundle', 
                        bundle_type = 'custom', 
                        rules = [
                            sysdig_client.models.bundle_rule.BundleRule(
                                rule_type = 'vulnDenyList', 
                                predicates = [{"type":"vulnSeverity","extra":{"level":"high"}}], 
                                rule_id = '42', )
                            ], )
                    ],
        )
        """

    def testListBundlesResponse(self):
        """Test ListBundlesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
