# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.rules_response_v1_data_groups_inner_rules_inner_alerts_inner import RulesResponseV1DataGroupsInnerRulesInnerAlertsInner

class TestRulesResponseV1DataGroupsInnerRulesInnerAlertsInner(unittest.TestCase):
    """RulesResponseV1DataGroupsInnerRulesInnerAlertsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RulesResponseV1DataGroupsInnerRulesInnerAlertsInner:
        """Test RulesResponseV1DataGroupsInnerRulesInnerAlertsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RulesResponseV1DataGroupsInnerRulesInnerAlertsInner`
        """
        model = RulesResponseV1DataGroupsInnerRulesInnerAlertsInner()
        if include_optional:
            return RulesResponseV1DataGroupsInnerRulesInnerAlertsInner(
                state = 'firing',
                active_at = '2023-10-05T14:30Z',
                value = '1e+00'
            )
        else:
            return RulesResponseV1DataGroupsInnerRulesInnerAlertsInner(
                state = 'firing',
                active_at = '2023-10-05T14:30Z',
                value = '1e+00',
        )
        """

    def testRulesResponseV1DataGroupsInnerRulesInnerAlertsInner(self):
        """Test RulesResponseV1DataGroupsInnerRulesInnerAlertsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
