# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.pkg_vuln_failure import PkgVulnFailure

class TestPkgVulnFailure(unittest.TestCase):
    """PkgVulnFailure unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PkgVulnFailure:
        """Test PkgVulnFailure
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PkgVulnFailure`
        """
        model = PkgVulnFailure()
        if include_optional:
            return PkgVulnFailure(
                description = 'description',
                package_ref = '2772f8a6c73fa17',
                vulnerability_ref = '71af37c6a8f2772',
                risk_accept_refs = [
                    'e6b4b0d3255bfef'
                    ]
            )
        else:
            return PkgVulnFailure(
                description = 'description',
        )
        """

    def testPkgVulnFailure(self):
        """Test PkgVulnFailure"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
