# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.gssapi_connection_info_kafka import GssapiConnectionInfoKafka

class TestGssapiConnectionInfoKafka(unittest.TestCase):
    """GssapiConnectionInfoKafka unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GssapiConnectionInfoKafka:
        """Test GssapiConnectionInfoKafka
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GssapiConnectionInfoKafka`
        """
        model = GssapiConnectionInfoKafka()
        if include_optional:
            return GssapiConnectionInfoKafka(
                auth = 'gssapi',
                principal = 'myprincipal',
                realm = 'myrealm',
                service = 'myservice',
                krb5 = '[libdefaults] default_realm = SYSDIG.COM default_tkt_enctypes = des3-hmac-sha1 des-cbc-crc default_tgs_enctypes = des3-hmac-sha1 des-cbc-crc dns_lookup_kdc = true dns_lookup_realm = false [realms] SYSDIG.COM = { kdc = kerberos.sysdig.com kdc = kerberos-1.sysdig.com kdc = kerberos-2.sysdig.com:750 admin_server = kerberos.sysdig.com master_kdc = kerberos.sysdig.com default_domain = sysdig.com } [domain_realm] .sysdig.com = SYSDIG.COM sysdig.com = SYSDIG.COM [logging] kdc = SYSLOG:INFO admin_server = FILE=/var/kadm5.log'
            )
        else:
            return GssapiConnectionInfoKafka(
                auth = 'gssapi',
                principal = 'myprincipal',
                realm = 'myrealm',
                service = 'myservice',
                krb5 = '[libdefaults] default_realm = SYSDIG.COM default_tkt_enctypes = des3-hmac-sha1 des-cbc-crc default_tgs_enctypes = des3-hmac-sha1 des-cbc-crc dns_lookup_kdc = true dns_lookup_realm = false [realms] SYSDIG.COM = { kdc = kerberos.sysdig.com kdc = kerberos-1.sysdig.com kdc = kerberos-2.sysdig.com:750 admin_server = kerberos.sysdig.com master_kdc = kerberos.sysdig.com default_domain = sysdig.com } [domain_realm] .sysdig.com = SYSDIG.COM sysdig.com = SYSDIG.COM [logging] kdc = SYSLOG:INFO admin_server = FILE=/var/kadm5.log',
        )
        """

    def testGssapiConnectionInfoKafka(self):
        """Test GssapiConnectionInfoKafka"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
