# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.get_microsoft_sentinel_integration_response import GetMicrosoftSentinelIntegrationResponse

class TestGetMicrosoftSentinelIntegrationResponse(unittest.TestCase):
    """GetMicrosoftSentinelIntegrationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMicrosoftSentinelIntegrationResponse:
        """Test GetMicrosoftSentinelIntegrationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMicrosoftSentinelIntegrationResponse`
        """
        model = GetMicrosoftSentinelIntegrationResponse()
        if include_optional:
            return GetMicrosoftSentinelIntegrationResponse(
                name = 'name',
                is_enabled = True,
                type = 'SYSLOG',
                channels = [SECURE_EVENTS_POLICIES, ACTIVITY_AUDIT],
                id = 1,
                connection_info = sysdig_client.models.microsoft_sentinel.Microsoft Sentinel(
                    workspace_id = '578aef60-81be-4d38-a278-ec77925edcf0', )
            )
        else:
            return GetMicrosoftSentinelIntegrationResponse(
                name = 'name',
                is_enabled = True,
                type = 'SYSLOG',
                channels = [SECURE_EVENTS_POLICIES, ACTIVITY_AUDIT],
                id = 1,
                connection_info = sysdig_client.models.microsoft_sentinel.Microsoft Sentinel(
                    workspace_id = '578aef60-81be-4d38-a278-ec77925edcf0', ),
        )
        """

    def testGetMicrosoftSentinelIntegrationResponse(self):
        """Test GetMicrosoftSentinelIntegrationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
