# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.notification_channel_response_v1 import NotificationChannelResponseV1

class TestNotificationChannelResponseV1(unittest.TestCase):
    """NotificationChannelResponseV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotificationChannelResponseV1:
        """Test NotificationChannelResponseV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NotificationChannelResponseV1`
        """
        model = NotificationChannelResponseV1()
        if include_optional:
            return NotificationChannelResponseV1(
                team_id = 13,
                is_enabled = False,
                name = 'Sample Notification Channel Name',
                has_test_notification_enabled = False,
                type = 'EMAIL',
                customer_id = 12,
                id = 1,
                version = 1,
                created_on = '2017-07-21T17:32:28Z',
                modified_on = '2017-07-21T17:32:28Z'
            )
        else:
            return NotificationChannelResponseV1(
                name = 'Sample Notification Channel Name',
                type = 'EMAIL',
        )
        """

    def testNotificationChannelResponseV1(self):
        """Test NotificationChannelResponseV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
