# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.update_notification_channel_request_v1 import UpdateNotificationChannelRequestV1

class TestUpdateNotificationChannelRequestV1(unittest.TestCase):
    """UpdateNotificationChannelRequestV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateNotificationChannelRequestV1:
        """Test UpdateNotificationChannelRequestV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateNotificationChannelRequestV1`
        """
        model = UpdateNotificationChannelRequestV1()
        if include_optional:
            return UpdateNotificationChannelRequestV1(
                team_id = 13,
                is_enabled = False,
                name = 'Sample Notification Channel Name',
                has_test_notification_enabled = False,
                type = 'EMAIL',
                version = 1
            )
        else:
            return UpdateNotificationChannelRequestV1(
                name = 'Sample Notification Channel Name',
                type = 'EMAIL',
        )
        """

    def testUpdateNotificationChannelRequestV1(self):
        """Test UpdateNotificationChannelRequestV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
