# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.cisa_kev_publish_date_extra import CisaKevPublishDateExtra

class TestCisaKevPublishDateExtra(unittest.TestCase):
    """CisaKevPublishDateExtra unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CisaKevPublishDateExtra:
        """Test CisaKevPublishDateExtra
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CisaKevPublishDateExtra`
        """
        model = CisaKevPublishDateExtra()
        if include_optional:
            return CisaKevPublishDateExtra(
                days = 3
            )
        else:
            return CisaKevPublishDateExtra(
        )
        """

    def testCisaKevPublishDateExtra(self):
        """Test CisaKevPublishDateExtra"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
