# coding: utf-8

"""
Sysdig Public API

Sysdig Public API.

The version of the OpenAPI document: 1.1.1
Contact: info@sysdig.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from sysdig_client.models.global_sso_settings_response_v1 import GlobalSsoSettingsResponseV1


class TestGlobalSsoSettingsResponseV1(unittest.TestCase):
    """GlobalSsoSettingsResponseV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GlobalSsoSettingsResponseV1:
        """Test GlobalSsoSettingsResponseV1
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GlobalSsoSettingsResponseV1`
        """
        model = GlobalSsoSettingsResponseV1()
        if include_optional:
            return GlobalSsoSettingsResponseV1(
                is_password_login_enabled = True
            )
        else:
            return GlobalSsoSettingsResponseV1(
        )
        """

    def testGlobalSsoSettingsResponseV1(self):
        """Test GlobalSsoSettingsResponseV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
