# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.services import Services

class TestServices(unittest.TestCase):
    """Services unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Services:
        """Test Services
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Services`
        """
        model = Services()
        if include_optional:
            return Services(
                certificate_id = 12345,
                service_type = 'EVENTS_FORWARDER',
                registered_at = '1970-01-01T00:00Z',
                service_id = '12345'
            )
        else:
            return Services(
                certificate_id = 12345,
                service_type = 'EVENTS_FORWARDER',
                registered_at = '1970-01-01T00:00Z',
                service_id = '12345',
        )
        """

    def testServices(self):
        """Test Services"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
