# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.api.teams_api import TeamsApi


class TestTeamsApi(unittest.TestCase):
    """TeamsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TeamsApi()

    def tearDown(self) -> None:
        pass

    def test_create_team_v1(self) -> None:
        """Test case for create_team_v1

        Create Team
        """
        pass

    def test_delete_team_by_id_v1(self) -> None:
        """Test case for delete_team_by_id_v1

        Delete Team
        """
        pass

    def test_delete_team_user_by_id_v1(self) -> None:
        """Test case for delete_team_user_by_id_v1

        Delete Membership
        """
        pass

    def test_get_team_by_id_v1(self) -> None:
        """Test case for get_team_by_id_v1

        Get Team
        """
        pass

    def test_get_team_user_by_id_v1(self) -> None:
        """Test case for get_team_user_by_id_v1

        Get Membership
        """
        pass

    def test_get_team_users_v1(self) -> None:
        """Test case for get_team_users_v1

        List Memberships
        """
        pass

    def test_get_teams_v1(self) -> None:
        """Test case for get_teams_v1

        List Teams
        """
        pass

    def test_save_team_user_v1(self) -> None:
        """Test case for save_team_user_v1

        Save Membership
        """
        pass

    def test_update_team_by_id_v1(self) -> None:
        """Test case for update_team_by_id_v1

        Update Team
        """
        pass


if __name__ == '__main__':
    unittest.main()
