# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.kubernetes import Kubernetes

class TestKubernetes(unittest.TestCase):
    """Kubernetes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Kubernetes:
        """Test Kubernetes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Kubernetes`
        """
        model = Kubernetes()
        if include_optional:
            return Kubernetes(
                id = '15cbf54e34df95404caad1c988cf7c42',
                timestamp = 1546300800000000000,
                type = 'kubernetes',
                hostname = 'ip-127-0-0-1',
                container_id = 'f8d4f71ab80b',
                resource = 'pods',
                sub_resource = 'exec',
                namespace = 'sysdigcloud',
                name = 'sysdigcloud-redis-75675f5897-7ci7o',
                source_addresses = ["127.0.0.1","192.168.0.1"],
                user = sysdig_client.models.user.User(
                    username = 'kubernetes-admin', 
                    groups = ["system:masters","system:authenticated"], ),
                user_agent = 'kubectl/v1.13.5 (linux/amd64) kubernetes/2166946',
                args = {"command":"bash","container":"redis"},
                labels = {
                    'key' : 'foo'
                    }
            )
        else:
            return Kubernetes(
                id = '15cbf54e34df95404caad1c988cf7c42',
                timestamp = 1546300800000000000,
                type = 'kubernetes',
                hostname = 'ip-127-0-0-1',
                container_id = 'f8d4f71ab80b',
                resource = 'pods',
                sub_resource = 'exec',
                namespace = 'sysdigcloud',
                name = 'sysdigcloud-redis-75675f5897-7ci7o',
                source_addresses = ["127.0.0.1","192.168.0.1"],
                user = sysdig_client.models.user.User(
                    username = 'kubernetes-admin', 
                    groups = ["system:masters","system:authenticated"], ),
                user_agent = 'kubectl/v1.13.5 (linux/amd64) kubernetes/2166946',
                args = {"command":"bash","container":"redis"},
        )
        """

    def testKubernetes(self):
        """Test Kubernetes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
