# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.wasted_workload_spend_data_response import WastedWorkloadSpendDataResponse

class TestWastedWorkloadSpendDataResponse(unittest.TestCase):
    """WastedWorkloadSpendDataResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WastedWorkloadSpendDataResponse:
        """Test WastedWorkloadSpendDataResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WastedWorkloadSpendDataResponse`
        """
        model = WastedWorkloadSpendDataResponse()
        if include_optional:
            return WastedWorkloadSpendDataResponse(
                total = sysdig_client.models.wasted_workload_spend_data_response_total.WastedWorkloadSpendDataResponse_total(
                    accrued = 31.59, 
                    estimated = 5.6, 
                    wasted = 25.73, ),
                group_by_data = [
                    {"group":{"kube_cluster_name":"test-k8s-cluster"},"accrued":26.59,"estimated":3.6,"wasted":22.99}
                    ]
            )
        else:
            return WastedWorkloadSpendDataResponse(
        )
        """

    def testWastedWorkloadSpendDataResponse(self):
        """Test WastedWorkloadSpendDataResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
