# coding: utf-8

"""
Sysdig Public API

Sysdig Public API.

The version of the OpenAPI document: 1.1.1
Contact: info@sysdig.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from sysdig_client.models.rules_response_v1 import RulesResponseV1


class TestRulesResponseV1(unittest.TestCase):
    """RulesResponseV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RulesResponseV1:
        """Test RulesResponseV1
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `RulesResponseV1`
        """
        model = RulesResponseV1()
        if include_optional:
            return RulesResponseV1(
                status = 'success',
                data = sysdig_client.models.rules_response_v1_data.RulesResponseV1_data(
                    groups = [
                        sysdig_client.models.rules_response_v1_data_groups_inner.RulesResponseV1_data_groups_inner(
                            name = 'HTTP Alerts',
                            interval = '30s',
                            rules = [
                                sysdig_client.models.rules_response_v1_data_groups_inner_rules_inner.RulesResponseV1_data_groups_inner_rules_inner(
                                    type = 'alerting',
                                    name = 'HighCPUUsage',
                                    query = 'avg by(instance) (rate(cpu_usage[5m])) > 0.9',
                                    duration = '5m',
                                    labels = {"severity":"critical"},
                                    annotations = {"description":"CPU usage is above 90% for more than 5 minutes."},
                                    alerts = [
                                        sysdig_client.models.rules_response_v1_data_groups_inner_rules_inner_alerts_inner.RulesResponseV1_data_groups_inner_rules_inner_alerts_inner(
                                            state = 'firing',
                                            active_at = '2023-10-05T14:30Z',
                                            value = '1e+00', )
                                        ], )
                                ], )
                        ], ),
                warnings = [],
                infos = []
            )
        else:
            return RulesResponseV1(
        )
        """

    def testRulesResponseV1(self):
        """Test RulesResponseV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
