# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.create_service_account_request_v1 import CreateServiceAccountRequestV1

class TestCreateServiceAccountRequestV1(unittest.TestCase):
    """CreateServiceAccountRequestV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateServiceAccountRequestV1:
        """Test CreateServiceAccountRequestV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateServiceAccountRequestV1`
        """
        model = CreateServiceAccountRequestV1()
        if include_optional:
            return CreateServiceAccountRequestV1(
                name = 'CI/CD service api key',
                expiration_date = 1630326638135
            )
        else:
            return CreateServiceAccountRequestV1(
        )
        """

    def testCreateServiceAccountRequestV1(self):
        """Test CreateServiceAccountRequestV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
