# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.connection import Connection

class TestConnection(unittest.TestCase):
    """Connection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Connection:
        """Test Connection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Connection`
        """
        model = Connection()
        if include_optional:
            return Connection(
                id = '15cbf54e34df95404caad1c988cf7c42',
                timestamp = 1546300800000000000,
                type = 'connection',
                cmdline = 'pg_isready --host 10.32.0.8',
                comm = 'pg_isready',
                dns_domains = ["sysdig.com"],
                container_id = 'f8d4f71ab80b',
                pid = 123,
                process_name = 'curl',
                client_ipv4 = '127.0.0.1',
                client_port = 31234,
                server_ipv4 = '127.0.0.1',
                server_port = 80,
                direction = 'in',
                l4protocol = 'tcp',
                hostname = 'ip-127-0-0-1',
                tty = 32444,
                labels = {
                    'key' : 'foo'
                    }
            )
        else:
            return Connection(
                id = '15cbf54e34df95404caad1c988cf7c42',
                timestamp = 1546300800000000000,
                type = 'connection',
                cmdline = 'pg_isready --host 10.32.0.8',
                comm = 'pg_isready',
                dns_domains = ["sysdig.com"],
                container_id = 'f8d4f71ab80b',
                pid = 123,
                process_name = 'curl',
                client_ipv4 = '127.0.0.1',
                client_port = 31234,
                server_ipv4 = '127.0.0.1',
                server_port = 80,
                direction = 'in',
                l4protocol = 'tcp',
                hostname = 'ip-127-0-0-1',
                tty = 32444,
        )
        """

    def testConnection(self):
        """Test Connection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
