# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.workload_cost_trends_data_response_current_range import WorkloadCostTrendsDataResponseCurrentRange

class TestWorkloadCostTrendsDataResponseCurrentRange(unittest.TestCase):
    """WorkloadCostTrendsDataResponseCurrentRange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkloadCostTrendsDataResponseCurrentRange:
        """Test WorkloadCostTrendsDataResponseCurrentRange
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkloadCostTrendsDataResponseCurrentRange`
        """
        model = WorkloadCostTrendsDataResponseCurrentRange()
        if include_optional:
            return WorkloadCostTrendsDataResponseCurrentRange(
                start_date = 'Sun Feb 16 18:00:00 CST 2025',
                end_date = 'Tue Feb 18 18:00:00 CST 2025'
            )
        else:
            return WorkloadCostTrendsDataResponseCurrentRange(
                start_date = 'Sun Feb 16 18:00:00 CST 2025',
                end_date = 'Tue Feb 18 18:00:00 CST 2025',
        )
        """

    def testWorkloadCostTrendsDataResponseCurrentRange(self):
        """Test WorkloadCostTrendsDataResponseCurrentRange"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
