# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.base_connection_info_mcm import BaseConnectionInfoMcm

class TestBaseConnectionInfoMcm(unittest.TestCase):
    """BaseConnectionInfoMcm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BaseConnectionInfoMcm:
        """Test BaseConnectionInfoMcm
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BaseConnectionInfoMcm`
        """
        model = BaseConnectionInfoMcm()
        if include_optional:
            return BaseConnectionInfoMcm(
                endpoint = 'https://mcm.mydomain.com:8443',
                account_id = 'id-mycluster-account',
                provider_id = 'sysdig-secure',
                note_name = 'note-name',
                is_insecure = False
            )
        else:
            return BaseConnectionInfoMcm(
                endpoint = 'https://mcm.mydomain.com:8443',
        )
        """

    def testBaseConnectionInfoMcm(self):
        """Test BaseConnectionInfoMcm"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
