# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.update_slack_notification_channel_request_v1 import UpdateSlackNotificationChannelRequestV1

class TestUpdateSlackNotificationChannelRequestV1(unittest.TestCase):
    """UpdateSlackNotificationChannelRequestV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateSlackNotificationChannelRequestV1:
        """Test UpdateSlackNotificationChannelRequestV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateSlackNotificationChannelRequestV1`
        """
        model = UpdateSlackNotificationChannelRequestV1()
        if include_optional:
            return UpdateSlackNotificationChannelRequestV1(
                options = None
            )
        else:
            return UpdateSlackNotificationChannelRequestV1(
                options = None,
        )
        """

    def testUpdateSlackNotificationChannelRequestV1(self):
        """Test UpdateSlackNotificationChannelRequestV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
