# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.update_service_accounts_notification_settings_request_v1 import UpdateServiceAccountsNotificationSettingsRequestV1

class TestUpdateServiceAccountsNotificationSettingsRequestV1(unittest.TestCase):
    """UpdateServiceAccountsNotificationSettingsRequestV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateServiceAccountsNotificationSettingsRequestV1:
        """Test UpdateServiceAccountsNotificationSettingsRequestV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateServiceAccountsNotificationSettingsRequestV1`
        """
        model = UpdateServiceAccountsNotificationSettingsRequestV1()
        if include_optional:
            return UpdateServiceAccountsNotificationSettingsRequestV1(
                is_enabled = True,
                notification_channel_ids = [
                    null
                    ],
                days_before_expiry = [
                    3
                    ]
            )
        else:
            return UpdateServiceAccountsNotificationSettingsRequestV1(
                is_enabled = True,
                notification_channel_ids = [
                    null
                    ],
                days_before_expiry = [
                    3
                    ],
        )
        """

    def testUpdateServiceAccountsNotificationSettingsRequestV1(self):
        """Test UpdateServiceAccountsNotificationSettingsRequestV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
