# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.response_list_disabled_metrics_v1 import ResponseListDisabledMetricsV1

class TestResponseListDisabledMetricsV1(unittest.TestCase):
    """ResponseListDisabledMetricsV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseListDisabledMetricsV1:
        """Test ResponseListDisabledMetricsV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseListDisabledMetricsV1`
        """
        model = ResponseListDisabledMetricsV1()
        if include_optional:
            return ResponseListDisabledMetricsV1(
                data = [
                    sysdig_client.models.list_job_and_disabled_metrics_v1.ListJobAndDisabledMetricsV1(
                        job_name = 'k8s-pods', 
                        metrics = [
                            sysdig_client.models.metric_v1.MetricV1(
                                metric_name = 'apache_accesses_total', 
                                modified_date = '2017-07-21T17:32:28Z', 
                                user_id = 1234, 
                                user_name = 'John Smith', )
                            ], )
                    ],
                errors = [
                    sysdig_client.models.metric_error_v1.MetricErrorV1(
                        metric_name = 'apache_accesses_total', 
                        job_name = 'k8s-pods', 
                        message = 'This is not a valid metric name.', )
                    ]
            )
        else:
            return ResponseListDisabledMetricsV1(
                data = [
                    sysdig_client.models.list_job_and_disabled_metrics_v1.ListJobAndDisabledMetricsV1(
                        job_name = 'k8s-pods', 
                        metrics = [
                            sysdig_client.models.metric_v1.MetricV1(
                                metric_name = 'apache_accesses_total', 
                                modified_date = '2017-07-21T17:32:28Z', 
                                user_id = 1234, 
                                user_name = 'John Smith', )
                            ], )
                    ],
        )
        """

    def testResponseListDisabledMetricsV1(self):
        """Test ResponseListDisabledMetricsV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
