# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.create_group_mapping_request_v1 import CreateGroupMappingRequestV1

class TestCreateGroupMappingRequestV1(unittest.TestCase):
    """CreateGroupMappingRequestV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateGroupMappingRequestV1:
        """Test CreateGroupMappingRequestV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateGroupMappingRequestV1`
        """
        model = CreateGroupMappingRequestV1()
        if include_optional:
            return CreateGroupMappingRequestV1(
                group_name = 'Admins_Mapped_Group',
                standard_team_role = 'ROLE_TEAM_READ',
                custom_team_role_id = 1,
                is_admin = False,
                team_map = sysdig_client.models.team_map.Team Map(
                    is_for_all_teams = False, 
                    team_ids = [154,187], ),
                weight = 2
            )
        else:
            return CreateGroupMappingRequestV1(
                group_name = 'Admins_Mapped_Group',
                team_map = sysdig_client.models.team_map.Team Map(
                    is_for_all_teams = False, 
                    team_ids = [154,187], ),
        )
        """

    def testCreateGroupMappingRequestV1(self):
        """Test CreateGroupMappingRequestV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
