# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.unit_pricing_v1 import UnitPricingV1

class TestUnitPricingV1(unittest.TestCase):
    """UnitPricingV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnitPricingV1:
        """Test UnitPricingV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnitPricingV1`
        """
        model = UnitPricingV1()
        if include_optional:
            return UnitPricingV1(
                cpu = 0.031611,
                ram = 0.004237,
                storage = 0.00005479452,
                spot_cpu = 1.337,
                spot_ram = 1.337
            )
        else:
            return UnitPricingV1(
                cpu = 0.031611,
                ram = 0.004237,
                storage = 0.00005479452,
        )
        """

    def testUnitPricingV1(self):
        """Test UnitPricingV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
