# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.risk_accepted_response import RiskAcceptedResponse

class TestRiskAcceptedResponse(unittest.TestCase):
    """RiskAcceptedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RiskAcceptedResponse:
        """Test RiskAcceptedResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RiskAcceptedResponse`
        """
        model = RiskAcceptedResponse()
        if include_optional:
            return RiskAcceptedResponse(
                id = '17af8bade67c9a208e632df001fcea2c',
                expiration_date = 'Mon Feb 26 18:00:00 CST 2024',
                created_at = '2024-01-22T08:51:46.016464Z',
                updated_at = '2024-02-22T08:51:46.016464Z',
                status = 'active',
                created_by = 'user@sysdig.com',
                updated_by = 'user@sysdig.com',
                entity_value = 'CVE-1234-56789',
                reason = 'RiskTransferred',
                description = 'vulnerability cannot be removed manually',
                stages = [runtime, pipeline, registry],
                entity_type = 'imageName',
                context = None
            )
        else:
            return RiskAcceptedResponse(
                id = '17af8bade67c9a208e632df001fcea2c',
                status = 'active',
                entity_value = 'CVE-1234-56789',
                reason = 'RiskTransferred',
                description = 'vulnerability cannot be removed manually',
                entity_type = 'imageName',
                context = None,
        )
        """

    def testRiskAcceptedResponse(self):
        """Test RiskAcceptedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
