# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.scope_v1 import ScopeV1

class TestScopeV1(unittest.TestCase):
    """ScopeV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScopeV1:
        """Test ScopeV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScopeV1`
        """
        model = ScopeV1()
        if include_optional:
            return ScopeV1(
                type = 'PROMETHEUS_REMOTE_WRITE',
                expression = 'kubernetes.cluster.name in ("test-env")'
            )
        else:
            return ScopeV1(
                type = 'PROMETHEUS_REMOTE_WRITE',
                expression = 'kubernetes.cluster.name in ("test-env")',
        )
        """

    def testScopeV1(self):
        """Test ScopeV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
