# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API enables you to deep-dive into specific security events.

    The version of the OpenAPI document: 1.2.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.sequence_inner import SequenceInner

class TestSequenceInner(unittest.TestCase):
    """SequenceInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SequenceInner:
        """Test SequenceInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SequenceInner`
        """
        model = SequenceInner()
        if include_optional:
            return SequenceInner(
                event_id = '9aca10ca-481a-4ab7-b8fa-929c1ebf4c18',
                event_name = 'CreateUser',
                event_time = '2024-08-11T23:48:40Z',
                ingestion_id = '41157131027',
                region = 'us-east-1',
                source = 'aws',
                source_ip_address = '1.1.1.1',
                sub_ingestion_id = 'us-east-1'
            )
        else:
            return SequenceInner(
                event_id = '9aca10ca-481a-4ab7-b8fa-929c1ebf4c18',
                event_name = 'CreateUser',
                event_time = '2024-08-11T23:48:40Z',
                ingestion_id = '41157131027',
                region = 'us-east-1',
                source = 'aws',
                source_ip_address = '1.1.1.1',
                sub_ingestion_id = 'us-east-1',
        )
        """

    def testSequenceInner(self):
        """Test SequenceInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
