# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.entity_definition import EntityDefinition

class TestEntityDefinition(unittest.TestCase):
    """EntityDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EntityDefinition:
        """Test EntityDefinition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EntityDefinition`
        """
        model = EntityDefinition()
        if include_optional:
            return EntityDefinition(
                type = 'Field',
                alias = 'name',
                definition = sysdig_client.models.entity_definition_definition.EntityDefinition_definition(
                    def_type = 'Field', 
                    name = 'name', 
                    type = 'String', 
                    hidden = False, )
            )
        else:
            return EntityDefinition(
                type = 'Field',
                definition = sysdig_client.models.entity_definition_definition.EntityDefinition_definition(
                    def_type = 'Field', 
                    name = 'name', 
                    type = 'String', 
                    hidden = False, ),
        )
        """

    def testEntityDefinition(self):
        """Test EntityDefinition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
