# coding: utf-8

"""
Sysdig Public API

Sysdig Public API.

The version of the OpenAPI document: 1.1.1
Contact: info@sysdig.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from sysdig_client.models.series_response_v1 import SeriesResponseV1


class TestSeriesResponseV1(unittest.TestCase):
    """SeriesResponseV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SeriesResponseV1:
        """Test SeriesResponseV1
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SeriesResponseV1`
        """
        model = SeriesResponseV1()
        if include_optional:
            return SeriesResponseV1(
                status = 'success',
                data = [{"__name__":"up","instance":"localhost:9090","job":"prometheus"},{"__name__":"process_start_time_seconds","instance":"localhost:9090","job":"prometheus"}],
                warnings = [],
                infos = []
            )
        else:
            return SeriesResponseV1(
        )
        """

    def testSeriesResponseV1(self):
        """Test SeriesResponseV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
