# coding: utf-8

"""
    Sysdig Secure Events Feed API

    Sysdig Secure Events Feed API enables you to deep-dive into specific security events.

    The version of the OpenAPI document: 1.2.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.policy_origin import PolicyOrigin

class TestPolicyOrigin(unittest.TestCase):
    """PolicyOrigin unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPolicyOrigin(self):
        """Test PolicyOrigin"""
        # inst = PolicyOrigin()

if __name__ == '__main__':
    unittest.main()
