# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.private_connection_info_microsoft_sentinel import PrivateConnectionInfoMicrosoftSentinel

class TestPrivateConnectionInfoMicrosoftSentinel(unittest.TestCase):
    """PrivateConnectionInfoMicrosoftSentinel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PrivateConnectionInfoMicrosoftSentinel:
        """Test PrivateConnectionInfoMicrosoftSentinel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PrivateConnectionInfoMicrosoftSentinel`
        """
        model = PrivateConnectionInfoMicrosoftSentinel()
        if include_optional:
            return PrivateConnectionInfoMicrosoftSentinel(
                secret = 'b29qb29jdWIyd2F5N0FoWThzYWhuZzZhaWdoMWVlcmFoM3BoZXRvZURpZTdlaWJhCg=='
            )
        else:
            return PrivateConnectionInfoMicrosoftSentinel(
        )
        """

    def testPrivateConnectionInfoMicrosoftSentinel(self):
        """Test PrivateConnectionInfoMicrosoftSentinel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
