# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.team_map_v1 import TeamMapV1

class TestTeamMapV1(unittest.TestCase):
    """TeamMapV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamMapV1:
        """Test TeamMapV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamMapV1`
        """
        model = TeamMapV1()
        if include_optional:
            return TeamMapV1(
                is_for_all_teams = False,
                team_ids = [154,187]
            )
        else:
            return TeamMapV1(
        )
        """

    def testTeamMapV1(self):
        """Test TeamMapV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
