# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.policy_summary import PolicySummary

class TestPolicySummary(unittest.TestCase):
    """PolicySummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PolicySummary:
        """Test PolicySummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PolicySummary`
        """
        model = PolicySummary()
        if include_optional:
            return PolicySummary(
                id = 1,
                name = 'Sysdig policy',
                identifier = 'sysdig-policy',
                description = 'Sysdig policy',
                stages = [
                    'runtime'
                    ]
            )
        else:
            return PolicySummary(
                id = 1,
                name = 'Sysdig policy',
                identifier = 'sysdig-policy',
                stages = [
                    'runtime'
                    ],
        )
        """

    def testPolicySummary(self):
        """Test PolicySummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
