# coding: utf-8

"""
    Sysdig Secure Events Feed API

    Sysdig Secure Events Feed API enables you to deep-dive into specific security events.

    The version of the OpenAPI document: 1.2.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.agentless_runtime_detection_content import AgentlessRuntimeDetectionContent

class TestAgentlessRuntimeDetectionContent(unittest.TestCase):
    """AgentlessRuntimeDetectionContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentlessRuntimeDetectionContent:
        """Test AgentlessRuntimeDetectionContent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentlessRuntimeDetectionContent`
        """
        model = AgentlessRuntimeDetectionContent()
        if include_optional:
            return AgentlessRuntimeDetectionContent(
                type = 'workloadRuntimeDetection',
                integration_id = '2U98T7RVNpAfveU6t9U6JoKVuZb',
                integration_type = 'cloudtrail',
                rule_name = 'Create Security Group Rule Allowing SSH Ingress',
                rule_type = 6,
                rule_tags = [
                    'AWS_IAM'
                    ],
                policy_id = 2,
                policy_origin = 'Sysdig',
                policy_notification_channel_ids = [
                    123
                    ],
                priority = 'error',
                output = 'Error Detected creation of security group rule allowing SSH ingress (requesting user=github-actions-ansible-molecule-role, requesting IP=1.2.3.4, account ID=123456789012, AWS region=us-east-1, arn=arn:aws:sts::0123456789012:assumed-role/github-actions-ansible-molecule-role/GitHubActions, security group=sg-121364e586677869e)',
                fields = None
            )
        else:
            return AgentlessRuntimeDetectionContent(
                type = 'workloadRuntimeDetection',
                integration_id = '2U98T7RVNpAfveU6t9U6JoKVuZb',
                integration_type = 'cloudtrail',
                rule_name = 'Create Security Group Rule Allowing SSH Ingress',
                rule_type = 6,
                policy_id = 2,
                policy_origin = 'Sysdig',
        )
        """

    def testAgentlessRuntimeDetectionContent(self):
        """Test AgentlessRuntimeDetectionContent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
