# coding: utf-8

"""
Sysdig Platform Zones Public API

Sysdig Platform Zones Public API.

The version of the OpenAPI document: 1.1.1
Contact: info@sysdig.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from sysdig_client.models.monitor_scope_label import MonitorScopeLabel


class TestMonitorScopeLabel(unittest.TestCase):
    """MonitorScopeLabel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MonitorScopeLabel:
        """Test MonitorScopeLabel
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `MonitorScopeLabel`
        """
        model = MonitorScopeLabel()
        if include_optional:
            return MonitorScopeLabel(
                key = 'kube_cluster_name',
                value = [
                    'myCluster'
                    ]
            )
        else:
            return MonitorScopeLabel(
        )
        """

    def testMonitorScopeLabel(self):
        """Test MonitorScopeLabel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
