# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.user_response_v1 import UserResponseV1

class TestUserResponseV1(unittest.TestCase):
    """UserResponseV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserResponseV1:
        """Test UserResponseV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserResponseV1`
        """
        model = UserResponseV1()
        if include_optional:
            return UserResponseV1(
                id = 1,
                email = 'john.doe@nomail.cc',
                first_name = 'john',
                last_name = 'doe',
                is_admin = False,
                activation_status = 'confirmed',
                date_created = '2017-07-21T17:32:28Z',
                last_updated = '2017-07-21T17:32:28Z',
                version = 1
            )
        else:
            return UserResponseV1(
        )
        """

    def testUserResponseV1(self):
        """Test UserResponseV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
