# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.label_matcher_v1 import LabelMatcherV1

class TestLabelMatcherV1(unittest.TestCase):
    """LabelMatcherV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LabelMatcherV1:
        """Test LabelMatcherV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LabelMatcherV1`
        """
        model = LabelMatcherV1()
        if include_optional:
            return LabelMatcherV1(
                label_name = 'myLabel',
                operator = 'EQUALS',
                value = 'regexExample[s]?'
            )
        else:
            return LabelMatcherV1(
                label_name = 'myLabel',
                operator = 'EQUALS',
                value = 'regexExample[s]?',
        )
        """

    def testLabelMatcherV1(self):
        """Test LabelMatcherV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
