# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.ms_teams_notification_channel_options_v1 import MsTeamsNotificationChannelOptionsV1

class TestMsTeamsNotificationChannelOptionsV1(unittest.TestCase):
    """MsTeamsNotificationChannelOptionsV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MsTeamsNotificationChannelOptionsV1:
        """Test MsTeamsNotificationChannelOptionsV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MsTeamsNotificationChannelOptionsV1`
        """
        model = MsTeamsNotificationChannelOptionsV1()
        if include_optional:
            return MsTeamsNotificationChannelOptionsV1(
                has_hiding_of_sensitive_info = True,
                url = 'https://xxxxxx.webhook.office.com/webhookb2/00000000-0000-0000-0000-000000000000@11111111-1111-1111-1111-111111111111/IncomingWebhook/00000000000000000000000000000000/22222222-2222-2222-2222-222222222222'
            )
        else:
            return MsTeamsNotificationChannelOptionsV1(
                url = 'https://xxxxxx.webhook.office.com/webhookb2/00000000-0000-0000-0000-000000000000@11111111-1111-1111-1111-111111111111/IncomingWebhook/00000000000000000000000000000000/22222222-2222-2222-2222-222222222222',
        )
        """

    def testMsTeamsNotificationChannelOptionsV1(self):
        """Test MsTeamsNotificationChannelOptionsV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
