# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.notification_channel_type_v1 import NotificationChannelTypeV1

class TestNotificationChannelTypeV1(unittest.TestCase):
    """NotificationChannelTypeV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNotificationChannelTypeV1(self):
        """Test NotificationChannelTypeV1"""
        # inst = NotificationChannelTypeV1()

if __name__ == '__main__':
    unittest.main()
