# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.update_kafka_integration_request_all_of_connection_info import UpdateKafkaIntegrationRequestAllOfConnectionInfo

class TestUpdateKafkaIntegrationRequestAllOfConnectionInfo(unittest.TestCase):
    """UpdateKafkaIntegrationRequestAllOfConnectionInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateKafkaIntegrationRequestAllOfConnectionInfo:
        """Test UpdateKafkaIntegrationRequestAllOfConnectionInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateKafkaIntegrationRequestAllOfConnectionInfo`
        """
        model = UpdateKafkaIntegrationRequestAllOfConnectionInfo()
        if include_optional:
            return UpdateKafkaIntegrationRequestAllOfConnectionInfo(
                brokers = [
                    'kafka.mydomain.com:9091'
                    ],
                topic = 'mytopic',
                balancer = 'murmur2',
                compression = 'gzip',
                is_tls_enabled = True,
                is_insecure = False,
                auth = 'gssapi',
                principal = 'myprincipal',
                realm = 'myrealm',
                service = 'myservice',
                krb5 = '[libdefaults] default_realm = SYSDIG.COM default_tkt_enctypes = des3-hmac-sha1 des-cbc-crc default_tgs_enctypes = des3-hmac-sha1 des-cbc-crc dns_lookup_kdc = true dns_lookup_realm = false [realms] SYSDIG.COM = { kdc = kerberos.sysdig.com kdc = kerberos-1.sysdig.com kdc = kerberos-2.sysdig.com:750 admin_server = kerberos.sysdig.com master_kdc = kerberos.sysdig.com default_domain = sysdig.com } [domain_realm] .sysdig.com = SYSDIG.COM sysdig.com = SYSDIG.COM [logging] kdc = SYSLOG:INFO admin_server = FILE=/var/kadm5.log',
                keytab = 'BQIAAAA3AAEAClNZU0RJRy5DT00ABnN5c2RpZwAAAAFlhdTkAQAXABCIRvfq7o+xF60Gvdgwt1hsAAAAAQ=='
            )
        else:
            return UpdateKafkaIntegrationRequestAllOfConnectionInfo(
                brokers = [
                    'kafka.mydomain.com:9091'
                    ],
                topic = 'mytopic',
                auth = 'gssapi',
                principal = 'myprincipal',
                realm = 'myrealm',
                service = 'myservice',
                krb5 = '[libdefaults] default_realm = SYSDIG.COM default_tkt_enctypes = des3-hmac-sha1 des-cbc-crc default_tgs_enctypes = des3-hmac-sha1 des-cbc-crc dns_lookup_kdc = true dns_lookup_realm = false [realms] SYSDIG.COM = { kdc = kerberos.sysdig.com kdc = kerberos-1.sysdig.com kdc = kerberos-2.sysdig.com:750 admin_server = kerberos.sysdig.com master_kdc = kerberos.sysdig.com default_domain = sysdig.com } [domain_realm] .sysdig.com = SYSDIG.COM sysdig.com = SYSDIG.COM [logging] kdc = SYSLOG:INFO admin_server = FILE=/var/kadm5.log',
        )
        """

    def testUpdateKafkaIntegrationRequestAllOfConnectionInfo(self):
        """Test UpdateKafkaIntegrationRequestAllOfConnectionInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
