# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.authenticated_connection_info_elasticsearch import AuthenticatedConnectionInfoElasticsearch

class TestAuthenticatedConnectionInfoElasticsearch(unittest.TestCase):
    """AuthenticatedConnectionInfoElasticsearch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthenticatedConnectionInfoElasticsearch:
        """Test AuthenticatedConnectionInfoElasticsearch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthenticatedConnectionInfoElasticsearch`
        """
        model = AuthenticatedConnectionInfoElasticsearch()
        if include_optional:
            return AuthenticatedConnectionInfoElasticsearch(
                endpoint = 'https://elastic.mydomain.com',
                index = 'main',
                is_insecure = False,
                auth = 'BASIC_AUTH',
                format = 'KV_PAIRS',
                secret = 'Zm9vOiRhcHIxJE9GRzNYeWJwJGNrTDBGSERBa29YWUlsSDkuY3lzVDAK'
            )
        else:
            return AuthenticatedConnectionInfoElasticsearch(
                endpoint = 'https://elastic.mydomain.com',
                index = 'main',
                auth = 'BASIC_AUTH',
                secret = 'Zm9vOiRhcHIxJE9GRzNYeWJwJGNrTDBGSERBa29YWUlsSDkuY3lzVDAK',
        )
        """

    def testAuthenticatedConnectionInfoElasticsearch(self):
        """Test AuthenticatedConnectionInfoElasticsearch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
