# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.saml_base_v1 import SamlBaseV1

class TestSamlBaseV1(unittest.TestCase):
    """SamlBaseV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SamlBaseV1:
        """Test SamlBaseV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SamlBaseV1`
        """
        model = SamlBaseV1()
        if include_optional:
            return SamlBaseV1(
                metadata_url = 'https://accounts.example.com/metadata',
                metadata_xml = '<EntityDescriptor entityID= "https://accounts.example.com">
',
                email_parameter = 'email',
                is_signature_validation_enabled = True,
                is_signed_assertion_enabled = True,
                is_destination_verification_enabled = True,
                is_encryption_support_enabled = True
            )
        else:
            return SamlBaseV1(
        )
        """

    def testSamlBaseV1(self):
        """Test SamlBaseV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
