# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.update_issue_type_request_v1 import UpdateIssueTypeRequestV1

class TestUpdateIssueTypeRequestV1(unittest.TestCase):
    """UpdateIssueTypeRequestV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateIssueTypeRequestV1:
        """Test UpdateIssueTypeRequestV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateIssueTypeRequestV1`
        """
        model = UpdateIssueTypeRequestV1()
        if include_optional:
            return UpdateIssueTypeRequestV1(
                jira_open_status_id = '1000',
                jira_in_progress_status_id = '1001',
                jira_closed_status_id = '1002',
                custom_field_ids = [
                    'custom-field-id'
                    ]
            )
        else:
            return UpdateIssueTypeRequestV1(
                jira_open_status_id = '1000',
                jira_in_progress_status_id = '1001',
                jira_closed_status_id = '1002',
                custom_field_ids = [
                    'custom-field-id'
                    ],
        )
        """

    def testUpdateIssueTypeRequestV1(self):
        """Test UpdateIssueTypeRequestV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
