# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.create_ibm_event_notifications_notification_channel_request_v1 import CreateIbmEventNotificationsNotificationChannelRequestV1

class TestCreateIbmEventNotificationsNotificationChannelRequestV1(unittest.TestCase):
    """CreateIbmEventNotificationsNotificationChannelRequestV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateIbmEventNotificationsNotificationChannelRequestV1:
        """Test CreateIbmEventNotificationsNotificationChannelRequestV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateIbmEventNotificationsNotificationChannelRequestV1`
        """
        model = CreateIbmEventNotificationsNotificationChannelRequestV1()
        if include_optional:
            return CreateIbmEventNotificationsNotificationChannelRequestV1(
                options = None
            )
        else:
            return CreateIbmEventNotificationsNotificationChannelRequestV1(
                options = None,
        )
        """

    def testCreateIbmEventNotificationsNotificationChannelRequestV1(self):
        """Test CreateIbmEventNotificationsNotificationChannelRequestV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
