# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.get_notification_channels_paginated_response_v1 import GetNotificationChannelsPaginatedResponseV1

class TestGetNotificationChannelsPaginatedResponseV1(unittest.TestCase):
    """GetNotificationChannelsPaginatedResponseV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetNotificationChannelsPaginatedResponseV1:
        """Test GetNotificationChannelsPaginatedResponseV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetNotificationChannelsPaginatedResponseV1`
        """
        model = GetNotificationChannelsPaginatedResponseV1()
        if include_optional:
            return GetNotificationChannelsPaginatedResponseV1(
                page = sysdig_client.models.offset_paginated_response_page.OffsetPaginatedResponse_page(
                    previous = '10', 
                    next = '30', 
                    total = 1, ),
                data = [
                    null
                    ]
            )
        else:
            return GetNotificationChannelsPaginatedResponseV1(
        )
        """

    def testGetNotificationChannelsPaginatedResponseV1(self):
        """Test GetNotificationChannelsPaginatedResponseV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
