# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sysdig_client.models.bom_metadata import BOMMetadata

class TestBOMMetadata(unittest.TestCase):
    """BOMMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BOMMetadata:
        """Test BOMMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BOMMetadata`
        """
        model = BOMMetadata()
        if include_optional:
            return BOMMetadata(
                timestamp = '2018-03-20T09:12:28Z',
                lifecycle = 'post-build',
                tools = sysdig_client.models.creation_tools.Creation Tools(),
                component = sysdig_client.models.sbom_component_schema.SBOM component schema(
                    type = 'library', 
                    name = 'tomcat-catalina', 
                    bom_ref = '5581fa94-9052-4e55-8b28-750f16e183be', 
                    version = '9.0.14', 
                    group = 'com.acme', 
                    purl = 'pkg:maven/com.acme/tomcat-catalina@9.0.14?packaging=jar', )
            )
        else:
            return BOMMetadata(
        )
        """

    def testBOMMetadata(self):
        """Test BOMMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
