# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ActionType(str, Enum):
    """
    Action type.
    """

    """
    allowed enum values
    """
    CAPTURE = 'capture'
    CONTAINER_KILLED = 'container_killed'
    CONTAINER_PAUSED = 'container_paused'
    CONTAINER_STOPPED = 'container_stopped'
    DRIFT_PREVENTED = 'drift_prevented'
    MALWARE_PREVENTED = 'malware_prevented'
    PROCESS_KILLED = 'process_killed'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ActionType from a JSON string"""
        return cls(json.loads(json_str))


