# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class BaseRiskAcceptedResponsePayload(BaseModel):
    """
    BaseRiskAcceptedResponsePayload
    """ # noqa: E501
    id: Optional[Annotated[str, Field(strict=True, max_length=512)]] = Field(default=None, description="The Accepted Risk ID")
    expiration_date: Optional[date] = Field(default=None, description="Date when the accepted risk will expire (in YYYY-MM-DD format)", alias="expirationDate")
    created_at: Optional[datetime] = Field(default=None, description="Date when the Accepted Risk was created", alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, description="Date when the Accepted Risk was updated", alias="updatedAt")
    status: Optional[StrictStr] = Field(default=None, description="Specifies whether the Accepted Risk is enabled or expired")
    created_by: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, description="User who created the risk acceptance", alias="createdBy")
    updated_by: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, description="User who last updated the risk acceptance", alias="updatedBy")
    __properties: ClassVar[List[str]] = ["id", "expirationDate", "createdAt", "updatedAt", "status", "createdBy", "updatedBy"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['active', 'expired']):
            raise ValueError("must be one of enum values ('active', 'expired')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BaseRiskAcceptedResponsePayload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BaseRiskAcceptedResponsePayload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "expirationDate": obj.get("expirationDate"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "status": obj.get("status"),
            "createdBy": obj.get("createdBy"),
            "updatedBy": obj.get("updatedBy")
        })
        return _obj


