# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class IntegrationChannel(str, Enum):
    """
    Type of data to forward
    """

    """
    allowed enum values
    """
    SECURE_EVENTS_POLICIES = 'SECURE_EVENTS_POLICIES'
    ACTIVITY_AUDIT = 'ACTIVITY_AUDIT'
    MONITOR_EVENTS = 'MONITOR_EVENTS'
    PLATFORM_AUDIT = 'PLATFORM_AUDIT'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IntegrationChannel from a JSON string"""
        return cls(json.loads(json_str))


