# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from sysdig_client.models.risk_accepted_response_all_of_context import RiskAcceptedResponseAllOfContext
from typing import Optional, Set
from typing_extensions import Self

class ListRiskAcceptedResponseAllOfData(BaseModel):
    """
    ListRiskAcceptedResponseAllOfData
    """ # noqa: E501
    entity_type: StrictStr = Field(description="The entity where the Accepted Risk will be applied.", alias="entityType")
    context: RiskAcceptedResponseAllOfContext
    id: Annotated[str, Field(strict=True, max_length=512)] = Field(description="The Accepted Risk ID")
    expiration_date: Optional[date] = Field(default=None, description="Date when the accepted risk will expire (in YYYY-MM-DD format)", alias="expirationDate")
    created_at: Optional[datetime] = Field(default=None, description="Date when the Accepted Risk was created", alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, description="Date when the Accepted Risk was updated", alias="updatedAt")
    status: StrictStr = Field(description="Specifies whether the Accepted Risk is enabled or expired")
    created_by: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, description="User who created the risk acceptance", alias="createdBy")
    updated_by: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, description="User who last updated the risk acceptance", alias="updatedBy")
    entity_value: Annotated[str, Field(min_length=1, strict=True, max_length=512)] = Field(description="A value to match with the entityType", alias="entityValue")
    reason: StrictStr = Field(description="Reason for acceptance")
    description: Annotated[str, Field(strict=True, max_length=512)] = Field(description="Description of why the accepted risk was created")
    stages: Optional[Annotated[List[StrictStr], Field(min_length=0, max_length=3)]] = Field(default=None, description="List of stages where the risk acceptance is applied, empty list enables risk acceptance for all the stages")
    __properties: ClassVar[List[str]] = ["entityType", "context", "id", "expirationDate", "createdAt", "updatedAt", "status", "createdBy", "updatedBy", "entityValue", "reason", "description", "stages"]

    @field_validator('entity_type')
    def entity_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['imageName', 'imagePrefix', 'imageSuffix', 'vulnerability', 'hostName', 'hostNameContains', 'imageNameContains', 'policyRule']):
            raise ValueError("must be one of enum values ('imageName', 'imagePrefix', 'imageSuffix', 'vulnerability', 'hostName', 'hostNameContains', 'imageNameContains', 'policyRule')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['active', 'expired']):
            raise ValueError("must be one of enum values ('active', 'expired')")
        return value

    @field_validator('reason')
    def reason_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['RiskTransferred', 'RiskAvoided', 'RiskMitigated', 'RiskOwned', 'RiskNotRelevant', 'Custom']):
            raise ValueError("must be one of enum values ('RiskTransferred', 'RiskAvoided', 'RiskMitigated', 'RiskOwned', 'RiskNotRelevant', 'Custom')")
        return value

    @field_validator('stages')
    def stages_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['runtime', 'pipeline', 'registry']):
                raise ValueError("each list item must be one of ('runtime', 'pipeline', 'registry')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListRiskAcceptedResponseAllOfData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of context
        if self.context:
            _dict['context'] = self.context.to_dict()
        # set to None if stages (nullable) is None
        # and model_fields_set contains the field
        if self.stages is None and "stages" in self.model_fields_set:
            _dict['stages'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListRiskAcceptedResponseAllOfData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "entityType": obj.get("entityType"),
            "context": RiskAcceptedResponseAllOfContext.from_dict(obj["context"]) if obj.get("context") is not None else None,
            "id": obj.get("id"),
            "expirationDate": obj.get("expirationDate"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "status": obj.get("status"),
            "createdBy": obj.get("createdBy"),
            "updatedBy": obj.get("updatedBy"),
            "entityValue": obj.get("entityValue"),
            "reason": obj.get("reason"),
            "description": obj.get("description"),
            "stages": obj.get("stages")
        })
        return _obj


