# coding: utf-8

"""
    Sysdig Secure Events Feed API

    Sysdig Secure Events Feed API enables you to deep-dive into specific security events.

    The version of the OpenAPI document: 1.2.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Originator(str, Enum):
    """
    Type of event: - policy - Agent-based runtime threat detection events - profilingDetection - Workload ML detections - falcocloud - Agentless threat detections - admissionController - Kubernetes admission control based posture events 
    """

    """
    allowed enum values
    """
    POLICY = 'policy'
    PROFILINGDETECTION = 'profilingDetection'
    FALCOCLOUD = 'falcocloud'
    ADMISSIONCONTROLLER = 'admissionController'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Originator from a JSON string"""
        return cls(json.loads(json_str))


