# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ResponderType(str, Enum):
    """
    The type of Responder executing an action.
    """

    """
    allowed enum values
    """
    HOST = 'HOST'
    CLUSTER = 'CLUSTER'
    CLOUD = 'CLOUD'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ResponderType from a JSON string"""
        return cls(json.loads(json_str))


