# coding: utf-8

"""
Sysdig Public API

Sysdig Public API.

The version of the OpenAPI document: 1.1.1
Contact: info@sysdig.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from sysdig_client.models.rules_response_v1_data_groups_inner_rules_inner import RulesResponseV1DataGroupsInnerRulesInner
from typing import Optional, Set
from typing_extensions import Self


class RulesResponseV1DataGroupsInner(BaseModel):
    """
    RulesResponseV1DataGroupsInner
    """  # noqa: E501

    name: Annotated[str, Field(strict=True, max_length=255)] = Field(description="Name of the rule group.")
    interval: Annotated[str, Field(strict=True, max_length=30)] = Field(description="Evaluation interval of the rule group.")
    rules: List[RulesResponseV1DataGroupsInnerRulesInner] = Field(description="List of rules in the group.")
    __properties: ClassVar[List[str]] = ["name", "interval", "rules"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RulesResponseV1DataGroupsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in rules (list)
        _items = []
        if self.rules:
            for _item_rules in self.rules:
                if _item_rules:
                    _items.append(_item_rules.to_dict())
            _dict["rules"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RulesResponseV1DataGroupsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "interval": obj.get("interval"),
                "rules": [RulesResponseV1DataGroupsInnerRulesInner.from_dict(_item) for _item in obj["rules"]]
                if obj.get("rules") is not None
                else None,
            }
        )
        return _obj
