# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ScopeTypeV1(str, Enum):
    """
    ScopeTypeV1
    """

    """
    allowed enum values
    """
    AGENT = 'AGENT'
    AWS_CLOUD_WATCH = 'AWS_CLOUD_WATCH'
    HOST_CONTAINER = 'HOST_CONTAINER'
    IBM_PLATFORM_METRICS = 'IBM_PLATFORM_METRICS'
    PROMETHEUS_REMOTE_WRITE = 'PROMETHEUS_REMOTE_WRITE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ScopeTypeV1 from a JSON string"""
        return cls(json.loads(json_str))


