# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TeamRoleV1(str, Enum):
    """
    The standard team role provided by Sysdig.
    """

    """
    allowed enum values
    """
    ROLE_TEAM_NONE = 'ROLE_TEAM_NONE'
    ROLE_TEAM_READ = 'ROLE_TEAM_READ'
    ROLE_TEAM_SERVICE_MANAGER = 'ROLE_TEAM_SERVICE_MANAGER'
    ROLE_TEAM_STANDARD = 'ROLE_TEAM_STANDARD'
    ROLE_TEAM_EDIT = 'ROLE_TEAM_EDIT'
    ROLE_TEAM_MANAGER = 'ROLE_TEAM_MANAGER'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TeamRoleV1 from a JSON string"""
        return cls(json.loads(json_str))


