# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class UpdateIntegrationRequestV1(BaseModel):
    """
    UpdateIntegrationRequestV1
    """ # noqa: E501
    name: Annotated[str, Field(strict=True, max_length=512)] = Field(description="Integration name.")
    is_enabled: StrictBool = Field(description="Integration enabled status.", alias="isEnabled")
    is_all_teams: StrictBool = Field(description="If **true**, the integration will be enabled for all teams. If **false**, the integration will be enabled for the teams specified in the *teamIds* field. ", alias="isAllTeams")
    team_ids: Annotated[List[Annotated[int, Field(strict=True, ge=0)]], Field(max_length=500)] = Field(description="List of Sysdig's internal team ids for which the integration will be enabled. This field is required if *isAllTeams* is **false**. ", alias="teamIds")
    jira_url: Annotated[str, Field(strict=True, max_length=512)] = Field(description="Customer's Jira URL.", alias="jiraUrl")
    jira_email: Annotated[str, Field(strict=True, max_length=512)] = Field(description="The user email associated with the Jira account.", alias="jiraEmail")
    jira_access_token: Annotated[str, Field(strict=True, max_length=512)] = Field(description="Jira access token for the provided Jira account.", alias="jiraAccessToken")
    jira_assignee: Optional[Annotated[str, Field(strict=True, max_length=512)]] = Field(description="The default assignee Jira account ID for this integration. Please refer to the [Jira documentation](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-user-search/#api-group-user-search \"Jira user documentation\") for more info. ", alias="jiraAssignee")
    jira_labels: Annotated[List[Annotated[str, Field(strict=True, max_length=512)]], Field(max_length=500)] = Field(description="The list of Jira labels available for this integration. Please refer to the [Jira documentation](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-labels/#api-group-labels \"Jira labels documentation\") for more info. ", alias="jiraLabels")
    parent_issue_type_id: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(description="Internal Sysdig's issue type id, which will act as a parent issue type for the integration. ", alias="parentIssueTypeId")
    child_issue_type_id: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(description="Internal Sysdig's issue type id, which will act as a child issue type for the integration. ", alias="childIssueTypeId")
    __properties: ClassVar[List[str]] = ["name", "isEnabled", "isAllTeams", "teamIds", "jiraUrl", "jiraEmail", "jiraAccessToken", "jiraAssignee", "jiraLabels", "parentIssueTypeId", "childIssueTypeId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateIntegrationRequestV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if jira_assignee (nullable) is None
        # and model_fields_set contains the field
        if self.jira_assignee is None and "jira_assignee" in self.model_fields_set:
            _dict['jiraAssignee'] = None

        # set to None if parent_issue_type_id (nullable) is None
        # and model_fields_set contains the field
        if self.parent_issue_type_id is None and "parent_issue_type_id" in self.model_fields_set:
            _dict['parentIssueTypeId'] = None

        # set to None if child_issue_type_id (nullable) is None
        # and model_fields_set contains the field
        if self.child_issue_type_id is None and "child_issue_type_id" in self.model_fields_set:
            _dict['childIssueTypeId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateIntegrationRequestV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "isEnabled": obj.get("isEnabled"),
            "isAllTeams": obj.get("isAllTeams"),
            "teamIds": obj.get("teamIds"),
            "jiraUrl": obj.get("jiraUrl"),
            "jiraEmail": obj.get("jiraEmail"),
            "jiraAccessToken": obj.get("jiraAccessToken"),
            "jiraAssignee": obj.get("jiraAssignee"),
            "jiraLabels": obj.get("jiraLabels"),
            "parentIssueTypeId": obj.get("parentIssueTypeId"),
            "childIssueTypeId": obj.get("childIssueTypeId")
        })
        return _obj


