# coding: utf-8

"""
Sysdig Public API

Sysdig Public API.

The version of the OpenAPI document: 1.1.1
Contact: info@sysdig.com
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from sysdig_client.models.date_range import DateRange
from sysdig_client.models.promql_matcher import PromqlMatcher
from typing import Set
from typing_extensions import Self


class WastedWorkloadDataRequest(BaseModel):
    """
    WastedWorkloadDataRequest
    """  # noqa: E501

    date_range: DateRange = Field(alias="dateRange")
    scope: Optional[Annotated[List[PromqlMatcher], Field(max_length=512)]] = Field(
        default=None, description="A list of PromQL-style filters"
    )
    group_by: Optional[
        Annotated[List[Annotated[str, Field(min_length=1, strict=True, max_length=1024)]], Field(max_length=7)]
    ] = Field(
        default=None,
        description="Specifies Prometheus labels to group the report data by. By default, the following labels will always be included:   - kube_cluster_name   - kube_namespace_name   - kube_workload_name A maximum of 7 additional custom labels can be specified. ",
        alias="groupBy",
    )
    __properties: ClassVar[List[str]] = ["dateRange", "scope", "groupBy"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WastedWorkloadDataRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of date_range
        if self.date_range:
            _dict["dateRange"] = self.date_range.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in scope (list)
        _items = []
        if self.scope:
            for _item_scope in self.scope:
                if _item_scope:
                    _items.append(_item_scope.to_dict())
            _dict["scope"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WastedWorkloadDataRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "dateRange": DateRange.from_dict(obj["dateRange"]) if obj.get("dateRange") is not None else None,
                "scope": [PromqlMatcher.from_dict(_item) for _item in obj["scope"]] if obj.get("scope") is not None else None,
                "groupBy": obj.get("groupBy"),
            }
        )
        return _obj
