# coding: utf-8

"""
    Sysdig Secure Client API

    Sysdig Secure Client API.

    The version of the OpenAPI document: 1.1.1
    Contact: info@sysdig.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated
from sysdig_client.models.sbom_result_response import SbomResultResponse

from sysdig_client.api_client import ApiClient, RequestSerialized
from sysdig_client.api_response import ApiResponse
from sysdig_client.rest import RESTResponseType


class SBOMApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_sbomv1beta1(
        self,
        asset_id: Annotated[Optional[Annotated[str, Field(strict=True, max_length=512)]], Field(description="The ID of the asset for which we want to retrieve the SBOM. It's the imageId for container-image and the hostId for hosts Provide this with assetType if not providing bomIdentifier ")] = None,
        asset_type: Annotated[Optional[StrictStr], Field(description="The type of the asset for which we want to retrieve the SBOM. Provide this with assetId if not providing bomIdentifier")] = None,
        bom_identifier: Annotated[Optional[Annotated[str, Field(strict=True, max_length=512)]], Field(description="The ID of a single SBOM. Either provide this or both assetId and assetType")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> SbomResultResponse:
        """Get SBOM

        Retrieve a SBOM (Software Bill Of Material) in CycloneDX format.

        :param asset_id: The ID of the asset for which we want to retrieve the SBOM. It's the imageId for container-image and the hostId for hosts Provide this with assetType if not providing bomIdentifier 
        :type asset_id: str
        :param asset_type: The type of the asset for which we want to retrieve the SBOM. Provide this with assetId if not providing bomIdentifier
        :type asset_type: str
        :param bom_identifier: The ID of a single SBOM. Either provide this or both assetId and assetType
        :type bom_identifier: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_sbomv1beta1_serialize(
            asset_id=asset_id,
            asset_type=asset_type,
            bom_identifier=bom_identifier,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SbomResultResponse",
            '400': "Error",
            '401': "Error",
            '403': "Error",
            '404': "Error",
            '406': "str",
            '429': "Error",
            '500': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_sbomv1beta1_with_http_info(
        self,
        asset_id: Annotated[Optional[Annotated[str, Field(strict=True, max_length=512)]], Field(description="The ID of the asset for which we want to retrieve the SBOM. It's the imageId for container-image and the hostId for hosts Provide this with assetType if not providing bomIdentifier ")] = None,
        asset_type: Annotated[Optional[StrictStr], Field(description="The type of the asset for which we want to retrieve the SBOM. Provide this with assetId if not providing bomIdentifier")] = None,
        bom_identifier: Annotated[Optional[Annotated[str, Field(strict=True, max_length=512)]], Field(description="The ID of a single SBOM. Either provide this or both assetId and assetType")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[SbomResultResponse]:
        """Get SBOM

        Retrieve a SBOM (Software Bill Of Material) in CycloneDX format.

        :param asset_id: The ID of the asset for which we want to retrieve the SBOM. It's the imageId for container-image and the hostId for hosts Provide this with assetType if not providing bomIdentifier 
        :type asset_id: str
        :param asset_type: The type of the asset for which we want to retrieve the SBOM. Provide this with assetId if not providing bomIdentifier
        :type asset_type: str
        :param bom_identifier: The ID of a single SBOM. Either provide this or both assetId and assetType
        :type bom_identifier: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_sbomv1beta1_serialize(
            asset_id=asset_id,
            asset_type=asset_type,
            bom_identifier=bom_identifier,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SbomResultResponse",
            '400': "Error",
            '401': "Error",
            '403': "Error",
            '404': "Error",
            '406': "str",
            '429': "Error",
            '500': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_sbomv1beta1_without_preload_content(
        self,
        asset_id: Annotated[Optional[Annotated[str, Field(strict=True, max_length=512)]], Field(description="The ID of the asset for which we want to retrieve the SBOM. It's the imageId for container-image and the hostId for hosts Provide this with assetType if not providing bomIdentifier ")] = None,
        asset_type: Annotated[Optional[StrictStr], Field(description="The type of the asset for which we want to retrieve the SBOM. Provide this with assetId if not providing bomIdentifier")] = None,
        bom_identifier: Annotated[Optional[Annotated[str, Field(strict=True, max_length=512)]], Field(description="The ID of a single SBOM. Either provide this or both assetId and assetType")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get SBOM

        Retrieve a SBOM (Software Bill Of Material) in CycloneDX format.

        :param asset_id: The ID of the asset for which we want to retrieve the SBOM. It's the imageId for container-image and the hostId for hosts Provide this with assetType if not providing bomIdentifier 
        :type asset_id: str
        :param asset_type: The type of the asset for which we want to retrieve the SBOM. Provide this with assetId if not providing bomIdentifier
        :type asset_type: str
        :param bom_identifier: The ID of a single SBOM. Either provide this or both assetId and assetType
        :type bom_identifier: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_sbomv1beta1_serialize(
            asset_id=asset_id,
            asset_type=asset_type,
            bom_identifier=bom_identifier,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SbomResultResponse",
            '400': "Error",
            '401': "Error",
            '403': "Error",
            '404': "Error",
            '406': "str",
            '429': "Error",
            '500': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_sbomv1beta1_serialize(
        self,
        asset_id,
        asset_type,
        bom_identifier,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if asset_id is not None:
            
            _query_params.append(('assetId', asset_id))
            
        if asset_type is not None:
            
            _query_params.append(('assetType', asset_type))
            
        if bom_identifier is not None:
            
            _query_params.append(('bomIdentifier', bom_identifier))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'bearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/secure/vulnerability/v1beta1/sboms',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


